[package]
name = "binance-async"
version = "0.1.1"
license = "MIT OR Apache-2.0"
authors = ["Guillaume Balaine igosuki.github@gmail.com"]
edition = "2018"

description = "Async Rust Library for the Binance API"
keywords = ["cryptocurrency", "trading", "binance"]
documentation = "https://docs.rs/crate/binance-rs-async/"
repository = "https://github.com/Igosuki/binance-rs-async"
readme = "README.md"

[lib]
name = "binance"
path = "src/lib.rs"

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.6"
error-chain = { version = "0.12", default-features = false }
ring = "0.16"
reqwest = { version = "0.10", features = ["json"] }
tungstenite = "0.10"
url = "2.1"
futures = "0.3"
chrono = "0.4"

[dev-dependencies]
csv = "1.0"
